version: '3'
services:
  nginx: 
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/log:/var/log/nginx/
        - ./nginx/cache/:/etc/nginx/cache
      ports:
        - 80:80
        - 443:443
      networks:
        - express-mongo-network
      depends_on:
        - api
      links:
        - api

  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - db:/data/db:Z
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
        - express-mongo-network

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    restart: always
    container_name: express_mongo_api_1
    environment:
      - NODE_ENV=dev
      - DB_HOST=db
    volumes:
      - ./src:/home/node/app/src
    expose: 
      - 9000
    links:
      - db
    depends_on:
      - db
    networks:
        - express-mongo-network

volumes:
  db:

networks: 
  express-mongo-network:
    driver: bridge